version: 2
jobs:
  build_deploy_functions:
    docker:
      - image: circleci/node:10.18.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - run: cd functions && npm install
      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}

      - run:
          name: Run build (tsc)
          working_directory: functions
          command: |
            npm run build

      - run:
          name: Run ESLint
          working_directory: functions
          command: |
            npm run lint

      - run:
          name: Run tests
          working_directory: functions
          command: |
            npm run test

      - deploy:
          name: if (master) Deploy to Firebase Functions
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./node_modules/firebase-tools/lib/bin/firebase.js deploy --token $FIREBASE_DEPLOY_TOKEN --only functions
            fi

  build_deploy_web:
    docker:
      - image: circleci/node:10.18.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "web/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - run: npm --prefix web/ install
      - save_cache:
          paths:
            - node_modules
            - web/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "web/package.json" }}

      - deploy:
          name: if (master ) Deploy to Firebase Hosting
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $GOOGLE_APPLICATION_CREDENTIALS_JSON > "`pwd`/auth.json"
              GOOGLE_APPLICATION_CREDENTIALS=`pwd`/auth.json ./node_modules/firebase-tools/lib/bin/firebase.js deploy --token $FIREBASE_DEPLOY_TOKEN --only hosting
            fi


workflows:
  version: 2
  main:
    jobs:
      - build_deploy_functions
      - build_deploy_web

  weekly:
    triggers:
      - schedule:
          cron: "5 9 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_deploy_web
