version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: cd functions && npm install

      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - deploy:
          name: Deploy Master to Firebase
          command: |
            ./node_modules/.bin/firebase use dansguiden  --token=$FIREBASE_DEPLOY_TOKEN
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
            fi
