version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: cd functions && npm install

      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test

      # - run: npm run lint

      - deploy:
          name: Deploy Master to Firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy-ci
            fi
