version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.18.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}-{{ checksum "web/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - run: cd functions && npm install
      - run: cd web && npm install
      - save_cache:
          paths:
            - node_modules
            - web/node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run build (tsc)
          working_directory: functions
          command: |
            npm run build

      - run:
          name: Run ESLint
          working_directory: functions
          command: |
            npm run lint

      - run:
          name: Run tests
          working_directory: functions
          command: |
            npm run test

      - deploy:
          name: Deploy Master to Firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy-ci
            fi
