# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Master Deploys

on:
  push:
    branches: [master]

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: functions/pnpm-lock.yaml

      - name: Install deps
        run: pnpm i

      - name: Run build (tsc)
        run:  pnpm run --filter functions build

      - name: Run lint (ESLint)
        run:  pnpm run --filter functions lint

      - name: Run test (Jest)
        run: pnpm run --filter functions test

      - name: Install firebase
        run: npm i -g firebase-tools@11.16.1

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Firebase Deploy (functions)
        run: firebase deploy --only functions

  deploy-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml

      - name: Install deps
        run: pnpm i --filter web

      - name: Run lint (ESLint)
        run: pnpm run --filter web lint

      - name: Install firebase
        run: npm i -g firebase-tools@11.16.1

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Firebase Deploy (hosting)
        run: firebase deploy --only hosting
