# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Master Deploys

on:
  push:
    branches: [master]

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Install deps
        run: npm ci --prefix functions

      - name: Run build (tsc)
        run: npm run --prefix functions build

      - name: Run lint (ESLint)
        run: npm run --prefix functions lint

      - name: Run test (Jest)
        run: npm run --prefix functions test

      - name: Install firebase
        run: npm i firebase-tools@11.16.1 -g

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Firebase Deploy (functions)
        run: firebase deploy --only functions

  deploy-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install deps
        run: npm ci --prefix web

      - name: Run lint (ESLint)
        run: npm run --prefix web lint

      - name: Install firebase
        run: npm i firebase-tools@11.16.1 -g

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Firebase Deploy (hosting)
        run: firebase deploy --only hosting
