# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  functions-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Install deps
        run: npm ci --prefix functions

      - name: Run lint (Jest)
        run: npm run --prefix functions test

  functions-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Install deps
        run: npm ci --prefix functions

      - name: Run lint (ESLint)
        run: npm run --prefix functions lint

  functions-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Install deps
        run: npm ci --prefix functions

      - name: Run lint (ESLint)
        run: npm run --prefix functions build

  web-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install deps
        run: npm ci --prefix web
      
      - name: Run prerender
        run: npm run --prefix web lint

